kumuluzee:
  name: image-analyzer-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://192.168.29.109:2379
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379
  health:
    servlet:
      mapping: /health
      enabled: true
    metrics:
      web-instrumentation:
        - name: image-analyzer-endpoint
          url-pattern: api/image-analyzer/*

app-properties:
  rekognition:
    enabled: true