kumuluzee:
  name: image-analyzer-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://192.168.29.109:2379
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379